export const ElementTypes = {
  header: "header",
  footer: "footer",
  main: "main",
  toc: "toc",
  content: "content",
  inner: "inner",
  headline: "headline",
  articles: "articles",
  vendor: "vendor",
  copyright: "copyright",
  license: "license",
  headlineWithMeta: "headlineWithMeta",
  comment: "comment",
  tocLink: "tocLink",
  googleTranslate: "googleTranslate",
  meta: "meta",
  icon: "icon",
  text: "text",
  links: "links",
  introduction: "introduction",
  issueDate: "issueDate",
  requestModule: "requestModule",
  pdf: "pdf",
  html: "html",
  label: "label",
};
