export const defaultComponents = [
  {
    id: "header",
    label: "Header",
    icon: "",
    name: "header",
    accept: [],
    path: "",
    attributes: {},
    children: [],
  },

  {
    id: "copyright",
    label: "Copyright",
    icon: "",
    name: "copyright",
    accept: [],
    path: "",
    attributes: {},
    children: [],
  },

  {
    id: "license",
    label: "License",
    icon: "",
    name: "license",
    accept: [],
    path: "",
    attributes: {},
    children: [],
  },

  {
    id: "vendor",
    label: "Vendor",
    icon: "",
    name: "vendor",
    accept: [],
    path: "",
    attributes: {},
    children: [],
  },

  {
    id: "footer",
    label: "Footer",
    icon: "",
    name: "footer",
    accept: ["copyright", "license", "vendor"],
    path: "",
    attributes: {},
    children: [],
  },
  {
    id: "main",
    label: "Main",
    icon: "",
    attributes: {
      template: "",
    },
    name: "main",
    accept: ["toc", "content"],
    path: "",
    children: [],
  },
  {
    id: "toc",
    label: "Toc",
    icon: "",
    name: "toc",
    attributes: {},
    accept: [],
    path: "",
    children: [],
  },
  {
    id: "content",
    label: "Content",
    icon: "",
    attributes: {
      template: "",
      dataIndex: "",
      classKey: "",
      recordFieldClass: [""],
    },
    name: "content",
    accept: ["inner"],
    path: "",
    children: [],
  },
  {
    id: "inner",
    label: "Inner",
    icon: "",
    name: "inner",
    accept: [""],
    attributes: {},
    path: "",
    children: [],
  },
  {
    id: "headline",
    label: "Headline",
    icon: "H",
    name: "headline",
    attributes: {},
    path: "",
    children: [],
  },
  {
    id: "articles",
    label: "Articles",
    icon: "A",
    name: "articles",
    attributes: {},
    path: "",
    children: [],
  },
];
